---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-22.04
    steps:
      - name: output vairable
        run: echo "the token is ${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: crpi-3gh5eupdtdopgxth.cn-shanghai.personal.cr.aliyuncs.com/recipe-app-api/recipe
          username: 1002922735983733
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: docker-compose run --rm app sh -c "python mange.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"